---
- hosts: all
  sudo: true
  vars_files:
    - [ "vars/vars.yml", "vars/vars.yml.default" ]
    - [ "vars/apt.yml", "vars/apt.yml.default" ]
    - [ "vars/postgresql.yml", "vars/postgresql.yml.default" ]
    - [ "vars/toba.yml", "vars/toba.yml.default" ]
  tasks:
    - name: Set System Encoding
      shell: echo LC_ALL="en_US.UTF-8" >> /etc/environment
    - { include: "tasks/apt.yml" }
    - { include: "tasks/apache2.yml" }
    - { include: "tasks/postgresql.yml" }
    - { include: "tasks/php.yml" }
    - { include: "handlers/services.yml", service: 'apache2', action: "restarted"}
    - { include: "handlers/services.yml", service: 'postgresql', action: "restarted"}
    - { include: "tasks/svn.yml" }
    - { include: "tasks/composer.yml" }
    - { include: "tasks/toba.yml" }
    - { include: "handlers/services.yml", service: 'apache2', action: "restarted"}
