---
- hosts: all
  sudo: true
  vars_files:
    - [ "vars/vars.yml", "vars/vars.yml.default" ]
    - [ "vars/apt.yml", "vars/apt.yml.default" ]
    - [ "vars/postgresql.yml", "vars/postgresql.yml.default" ]
    - [ "vars/toba.yml", "vars/toba.yml.default" ]
  tasks:
    - name: Set System Encoding
      shell: echo LC_ALL="en_US.UTF-8" >> /etc/environment
    - { include: "tasks/apt.yml" }
    - { include: "tasks/apache2.yml" }
    - { include: "tasks/postgresql.yml" }
    - name: Restart Services
      service: name={{ item }} state=restarted
      with_items:
        - apache2
        - postgresql
    - { include: "tasks/svn.yml" }
    - { include: "tasks/toba.yml" }
    - name: Restart Services
      service: name=apache2 state=restarted