- name: Set Proxy apt
  template:
    src={{template_path}}/proxy.conf.j2
    dest=/etc/apt/apt.conf.d/proxy.conf
  when: use_proxy == "yes"
- name: update apt cache
  apt: update_cache=yes
- name: upgrade packages
  apt: upgrade=safe
- name: Install LAPP env
  apt: name={{ item }} state=present
  with_items:
    - apache2
    - postgresql-{{ pg_version }}
    - php5
    - subversion
    - php5-pgsql
    - php5-gd
    - graphviz
    - htop
    - mc
